application: agilekalaftest
version: 5
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|jpeg))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|jpeg))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.app
  
libraries:
- name: PIL
  version: latest
